services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: MiroslavOCR
      MONGO_INITDB_ROOT_PASSWORD: Miroslav123
    volumes:
      - mongodb_data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  migrator:
    build:
      context: .
      dockerfile: mongo/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data

volumes:
  mongodb_data: